[project]
name = "fastapi-docker"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "fastapi>=0.115",
  "uvicorn[standard]>=0.30",
  "sqlmodel>=0.0.22",
  "psycopg2-binary>=2.9",
  "python-multipart>=0.0.20",
  "pyjwt[crypto]>=2.10.1",
  "pwdlib[argon2]>=0.3.0",
]

[tool.uv]


